import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount } from "wagmi";
import { useReadRaws } from "../blockchain/aggregates/read.raw";
import { useApprove } from "../blockchain/aggregates/approve.token";

function Home() {
  const [selectedHost, setSelectedHost] = useState(0);
  const [selectedStimulus, setSelectedStimulus] = useState(0);
  const { address, isConnected } = useAccount();
  const { hostData, stimulusData, isError, isLoading } = useReadRaws(address);
  // const { approveHost, approveStimulus } = useApprove(
  //   selectedHost,
  //   selectedStimulus
  // );

  return (
    <div className="">
      <Head>
        <title>Oppabear Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{address}</div>
      <Link href="/minting">mint mock nfts [host, stimulus]</Link>
      <ConnectButton label="Connect ME!!" accountStatus="address" />
      <div>
        {!address ? (
          <div>Loading ..</div>
        ) : (
          <div>
            <div>
              <label>Host</label>
              <select onChange={(event) => setSelectedHost(event.target.value)}>
                <option key={0} value={null}>
                  select
                </option>
                {hostData.map((data) => {
                  return (
                    <option key={data.toString()} value={data.toString()}>
                      {data.toString()}
                    </option>
                  );
                })}
              </select>
            </div>
            <div>
              <label>Stimulus</label>
              <select
                onChange={(event) => setSelectedStimulus(event.target.value)}
              >
                <option key={0} value={null}>
                  select
                </option>
                {stimulusData.map((data) => {
                  return (
                    <option key={data.toString()} value={data.toString()}>
                      {data.toString()}
                    </option>
                  );
                })}
              </select>
            </div>
            <div>
              <button onClick={() => approve()}>Approve</button>
              <button>Lock</button>
              <button>Fusion</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default Home;
